### ISSUE TITLE
integration touchups

### ISSUE THREAD

**Issue by Spaig** [dragonshardz/DPT-6-Rebuild#16]
- [x] add terra crystal to petal apothecary recipe
- [x] restore totemic staff recipe to vanilla-ish
- [x] tech greeble fungibility (canceled for being a total ballache)
- [x] determine which NC machines can be safely disabled since they're crap compared to other machines or duplicate functionality in a worse way
- [x] alloying shit, below

**Comment by Spaig** [comment]
- [ ] alternate enderium recipe
- [ ] greeble fungibility

**Comment by dragonshardz** [comment]
tweak alloys to follow IE smelter 1:1, induction furnace/source mod 1:2, arc furnace 1:4

- [x] disable crafting of two-input blends
- [x] steel: 1 iron ingot/dust plus 1 charcoal/dust
1. AK: 2 iron ingot/dust plus 2 charcoal/dust, 1 out
2. IF: 1 iron ingot/dust plus 1 charcoal/dust, 1 out
3. AF: 1 iron ingot/dust plus 1 charcoal/dust, 2 out
- [x] constantan
1. AK: 2 copper ingot/dust plus 2 nickel ingot/dust, 1 out
2. IF: 1 copper ingot/dust plus 1 nickel ingot/dust, 1 out
3. AF: 1 copper ingot/dust plus 1 nickel ingot/dust, 2 out
-  [x] electrum
1. AK: 2 silver ingot/dust plus 2 gold ingot/dust, 1 out
2. IF: 1 silver ingot/dust plus 1 gold ingot/dust, 1 out
3. AF: 1 silver ingot/dust plus 1 gold ingot/dust, 2 out
-  [x] titanium aluminide
1. AK: 3 titanium ingot/dust plus 1 aluminum ingot/dust, 1 out
2. IF: 7 titanium ingot/dust plus 3 aluminum ingot/dust, 3 out
3. AF: 7 titanium ingot/dust plus 3 aluminum ingot/dust, 6 out
-  [x] lumium
1. AK: 2 blend plus 2 sand, 1 out
2. IF: 1 blend plus 1 sand, 1 out
3. AF: Directly cook from base materials
- [x] signalum
1. AK: 2 blend plus 2 sand, 1 out
2. IF: 1 blend plus 1 sand, 1 out
3. AF: Directly cook from base materials
- [x] enderium
1. AK: 2 blend plus 2 sand, 1 out
2. IF: 1 blend plus 1 sand, 1 out
3. AF: Directly cook from base materials
- [x] fluxed electrum
1. AK: 2 blend plus 2 sand, 1 out
2. IF: 1 blend plus 1 sand, 1 out
3. AF: Directly cook from base materials
- [x] bronze
1. AK: 3 copper ingot/dust plus 1 tin ingot/dust, 2 out
2. IF: 3 copper ingot/dust plus 1 tin ingot/dust, 4 out
3. AF: 3 copper ingot/dust plus 1 tin ingot/dust, 8 out
- [x] invar
1. AK: 2 iron ingot/dust plus 1 nickel ingot/dust, 2 out
2. IF: 2 iron ingot/dust plus 1 nickel ingot/dust, 3 out
3. AF: 2 iron ingot/dust plus 1 nickel ingot/dust, 5 out
- [x] pig iron
1. AK: 1 iron ingot/dust plus 1 clay ball, 1 out
2. IF: 1 iron ingot/dust plus 1 clay ball, 2 out
3. AF: 2 iron ingot/dust plus 1 clay ball plus 2 rotten flesh, 4 out
- [x] titanium-iridium alloy
1. AK: 1 titanium ingot/dust plus 1 iridium ingot/dust, 1 out
2. IF: 1 titanium ingot/dust plus 1 iridium ingot/dust, 2 out
3. AF: 1 titanium ingot/dust plus 1 iridium ingot/dust, 4 out
- [x] aluminum brass - disable TiC alloying for fairness
1. AK: 1 copper ingot/dust plus 1 aluminum ingot/dust, 1 out
2. IF: 1 copper ingot/dust plus 1 aluminum ingot/dust, 2 out
3. AF: 1 copper ingot/dust plus 1 aluminum ingot/dust, 4 out
- [x] zircaloy
1. AK: 7 zirconium ingot/dust plus 1 tin ingot/dust, 4 out
2. IF: 7 zirconium ingot/dust plus 1 tin ingot/dust, 8 out
3. AF: 7 zirconium ingot/dust plus 1 tin ingot/dust, 16 out
- [x] silicon carbide
1. AK: 1 silicon plus 1 graphite ingot/dust, 1 out
2. IF: 1 silicon plus 1 graphite ingot/dust, 2 out
3. AF: 1 silicon plus 1 graphite ingot/dust, 4 out
- [x] HSLA steel - remove NC alloy furnace recipe?
1. AK: 15 carbon-manganese blend plus 1 steel ingot/dust, 8 out
2. IF: 15 carbon-manganese blend plus 1 1 steel ingot/dust, 16 out
3. AF: 15 carbon-manganese blend plus 1 1 steel ingot/dust, 32 out
- [x] manyullyn - normal ratio ores + sand in AK to get 1, normal ratio ores + sand as normal in IF, direct cook with increased output in AF
1. AK: 1 cobalt plus 1 ardite, 1 out
2. IF: 1 cobalt plus 1 ardite, 2 out
3. AF: 1 cobalt plus 1 ardite, 4 out
- [x] knightslime - seared brick and iron in AK to get 1, same double in IF, direct cook with increased output from equivalent TiC alloying in AF
1. AK: 1 iron ingot/dust plus 1 purple slimeball, 1 out
2. IF: 1 iron ingot/dust plus 1 purple slimeball, 2 out
3. AF: 4 iron ingot/dust plus 2 seared brick plus 1 purple slimeball, 8 out

**Comment by dragonshardz** [comment]
```
import mods.thermalexpansion.InductionSmelter;
var dustGold = <ore:dustGold>;
var dustSilver = <ore:dustSilver>;
InductionSmelter.removeRecipe(dustGold, dustSilver);
```
/ct syntax claims line 4 is missing the end-of-line ;

fuck this brokeass shitfuck pile of rickety-ratchet driftwood cocks

**Comment by Spaig** [comment]
spooky recipes:

- [x] mithminite
- [x] starmetal
- [x] livium
- [x] manasteel
- [x] thaumium
- [x] mithrillium
- [x] terrasteel
- [x] adaminite
- [x] void metal

**Comment by Spaig** [comment]
we did these!
