### ISSUE TITLE
Rewrite Quests

### ISSUE THREAD

**Issue by dragonshardz** [dragonshardz/DPT-6-Rebuild#3]
Get these from the archive of the old map and fix up to handle new stuff/tweaks

**Comment by Spaig** [comment]
- [x] import quest DB from DPT6
- [x] restructure quest lines conceptually
- [x] realign quest lines in the Book
- [x] finish totemic line
- [x] precursor portal ruin
- [x] finish botania line
- [x] finish thaumline
- [x] finish astraline
- [x] finish nukeline
- [x] fix up spaceline
- [x] Strength Behind the Scenes
- [x] There When You Need Me
- [x] And Gone Again When I'm Done
- [x] Writing for: And Gone Again When I'm done
- [x] update the actual quests
- [x] update quest text

**Comment by Spaig** [comment]
- [x] define landing spot for back to earth
- [x] define landing spot for moon
- [x] complete citadel
- [x] define portal ruin for quest
- [x] TURN OFF BQ EDIT MODE WHEN DONE

**Comment by Spaig** [comment]
(fargle is doing citadel)

**Comment by Spaig** [comment]
Quests are in place, pending finalization (we will turn this on when Fargle is ready)
