### ISSUE TITLE
Create the Mystic Mun

### ISSUE THREAD

**Issue by dragonshardz** [dragonshardz/DPT-6-Rebuild#4]
Pick out some Thamic Traveler's Dream biomes, paint up a biome map, and tweak the TTD configs to spawn this as dim 2 using the biome map

**Comment by Spaig** [comment]
- [X] Pick out some Thaumic Traveler's Dream biomes
- [X] create dimension preset
- [x] choose and define a portal material
- [x] tweak the TTD configs to spawn this as dim 2
- [x] check to see if dim generated properly
- [x] test portal

**Comment by Spaig** [comment]
the Moon rises
